export type SpeciesCard = {
  sci: string
  common: string
  light: 1 | 2 | 3 | 4
  water: "A" | "B" | "C"
  temp: string
  mist: "Sí" | "Mod" | "No"
  substrate: number
  fert: string
  toxic: boolean
  difficulty: 1 | 2 | 3
  ws: number
  ww: number
  flags: string
  aliases: string
}

// Formato: comun|cientifico|luz|riego|temp|pulv|sustrato|abono|tox|dif|diasVerano|diasInvierno|extra
const RAW = [
  "Lengua de suegra|Sansevieria trifasciata|4|C|15-28|No|2|M-Eq|1|1|12|20",
  "Lanza africana|Sansevieria cylindrica|4|C|15-28|No|2|M-Eq|1|1|12|20",
  "Planta ZZ|Zamioculcas zamiifolia|4|C|16-26|No|2|M-Eq|1|1|12|20",
  "Hoja de hierro|Aspidistra elatior|4|B|10-25|Sí|1|M-Eq|0|1|8|14",
  "Cinta|Chlorophytum comosum|3|B|15-25|Sí|1|M-Eq|0|1|6|10",
  "Aglaonema|Aglaonema commutatum|3|B|18-26|Sí|1|M-Eq|1|1|7|12",
  "Ficus gomero|Ficus elastica|2|B|16-27|No|1|M-Eq|1|1|7|12",
  "Ficus hoja violín|Ficus lyrata|2|B|18-27|No|1|M-Eq|1|2|7|10",
  "Ficus llorón|Ficus benjamina|2|B|16-26|No|1|M-Eq|1|1|6|10",
  "Bonsái de interior|Ficus microcarpa ginseng|2|B|18-26|Mod|1|M-Eq|1|2|6|10",
  "Árbol pulpo|Schefflera actinophylla|2|B|16-26|Sí|1|M-Eq|1|1|7|12",
  "Árbol dinero|Pachira aquatica|2|B|18-26|Sí|1|M-Eq|0|1|8|12",
  "Costilla de Adán|Monstera deliciosa|2|B|18-27|Sí|1|F-Eq|1|1|7|12",
  "Monstera adansonii|Monstera adansonii|2|B|18-27|Sí|1|F-Eq|1|1|6|10",
  "Filodendro trepador|Philodendron hederaceum|2|B|18-27|Sí|1|F-Eq|1|1|7|12",
  "Filodendro selloum|Philodendron bipinnatifidum|2|B|18-27|Sí|1|F-Eq|1|1|7|12",
  "Potos plateado|Scindapsus pictus|2|B|18-26|Sí|1|F-Eq|1|1|8|14",
  "Potos dorado|Epipremnum aureum|2|B|16-26|Sí|1|F-Eq|1|1|7|12",
  "Mini-monstera|Rhaphidophora tetrasperma|2|B|18-26|Sí|1|F-Eq|1|1|6|10",
  "Calathea orbifolia|Calathea orbifolia|3|A|18-24|Sí|1|F-Eq|0|3|5|8",
  "Calathea pavo real|Calathea makoyana|3|A|18-24|Sí|1|F-Eq|0|3|5|8",
  "Planta oración|Maranta leuconeura|3|A|18-24|Sí|1|F-Eq|0|3|5|8",
  "Ctenanthe|Ctenanthe burle-marxii|3|A|18-24|Sí|1|F-Eq|0|3|5|8",
  "Calathea lancifolia|Goeppertia insignis|3|A|18-24|Sí|1|F-Eq|0|3|5|8",
  "Árbol de jade|Crassula ovata|1|C|15-26|No|2|M-Eq|1|1|12|20",
  "Rosa alabastro|Echeveria elegans|1|C|15-25|No|2|M-Eq|0|1|12|20",
  "Cola de burro|Sedum morganianum|1|C|16-26|No|2|M-Eq|1|1|12|18",
  "Aloe vera|Aloe barbadensis|1|C|16-27|No|2|M-Eq|1|1|12|20",
  "Planta cebra|Haworthia fasciata|2|C|15-25|No|2|M-Eq|0|1|12|18",
  "Cactus de Navidad|Schlumbergera truncata|2|B|18-25|Sí|1|M-Flo|0|2|8|14",
  "Lirio de paz|Spathiphyllum wallisii|3|A|18-26|Sí|1|F-Flo|1|1|5|8",
  "Anturio|Anthurium andraeanum|2|B|18-26|Sí|1|F-Flo|1|2|6|9",
  "Orquídea mariposa|Phalaenopsis hybrida|2|B|18-28|No|4|M-Flo|0|2|8|12",
  "Violeta africana|Saintpaulia ionantha|3|B|18-24|No|1|M-Flo|0|2|6|9",
  "Kalanchoe|Kalanchoe blossfeldiana|1|C|16-26|No|2|M-Flo|1|1|9|14",
  "Begonia lunares|Begonia maculata|2|B|18-26|Sí|1|F-Flo|1|2|6|10",
  "Dracena tronco|Dracaena marginata|2|B|16-26|Sí|1|M-Eq|1|1|8|14",
  "Tronco Brasil|Dracaena fragrans|3|B|16-26|Sí|1|M-Eq|1|1|7|12",
  "Dracena manchada|Dracaena surculosa|3|B|18-26|Sí|1|M-Eq|1|1|7|12",
  "Palmera de salón|Chamaedorea elegans|3|B|16-24|Sí|1|M-Eq|0|1|6|10",
   "Areca|Dypsis lutescens|2|B|18-26|Sí|1|M-Eq|0|2|6|9||dypsis areca,palmera areca",
  "Pata de elefante|Beaucarnea recurvata|1|C|15-26|No|2|M-Eq|0|1|12|20",
  "Amor de hombre|Tradescantia zebrina|2|B|16-25|Sí|1|F-Eq|0|1|6|10",
  "Purpurina|Tradescantia pallida|1|B|16-25|Sí|1|F-Eq|0|1|6|10",
  "Collar de corazones|Ceropegia woodii|2|C|18-26|No|2|M-Eq|0|1|10|16",
  "Collar de perlas|Senecio rowleyanus|2|C|18-26|No|2|M-Eq|1|2|10|16",
  "Peperomia|Peperomia obtusifolia|3|B|18-26|Mod|1|M-Eq|0|1|8|14",
  "Helecho de Boston|Nephrolepis exaltata|3|A|16-24|Sí|1|F-Eq|0|2|4|7",
  "Helecho nido|Asplenium nidus|3|A|18-24|Sí|1|F-Eq|0|2|5|8",
  "Helecho resurrección|Pleopeltis polypodioides|3|A|18-24|Sí|1|F-Eq|0|2|5|8",
  "Alocasia tigre|Alocasia zebrina|2|A|20-27|Sí|1|F-Eq|1|3|4|7",
  "Alocasia polly|Alocasia amazonica|2|A|20-27|Sí|1|F-Eq|1|3|4|7",
  "Syngonium|Syngonium podophyllum|2|B|18-26|Sí|1|F-Eq|1|1|6|10",
  "Philodendron birkin|Philodendron birkin|2|B|18-26|Sí|1|F-Eq|1|2|6|10",
  "Philodendron gloriosum|Philodendron gloriosum|2|B|20-26|Sí|1|F-Eq|1|3|6|9",
  "Monstera plateada|Monstera siltepecana|2|B|18-26|Sí|1|F-Eq|1|2|6|10",
  "Planta de cera|Hoya carnosa|2|B|18-27|Sí|1|F-Eq|0|1|10|16",
  "Hoya linearis|Hoya linearis|2|B|18-26|Sí|1|F-Eq|0|2|9|14",
  "Peperomia sandía|Peperomia argyreia|3|B|18-26|Mod|1|M-Eq|0|2|7|12",
  "Peperomia arrugada|Peperomia caperata|3|B|18-26|Mod|1|M-Eq|0|2|7|12",
  "Higuera trepadora|Ficus pumila|3|B|16-26|No|1|M-Eq|1|1|6|10",
  "Ficus altissima|Ficus altissima|2|B|18-27|No|1|M-Eq|1|2|7|12",
  "Canción de India|Dracaena reflexa|2|B|16-26|Sí|1|M-Eq|1|1|7|12",
  "Ave paraíso pequeña|Strelitzia reginae|1|B|18-27|Sí|1|M-Flo|0|3|6|10",
  "Ave paraíso gigante|Strelitzia nicolai|1|B|18-27|Sí|1|M-Flo|0|3|6|10",
  "Palmera Kentia|Howea forsteriana|3|B|16-24|Sí|1|M-Eq|0|2|7|12",
  "Palmera majestad|Ravenea rivularis|2|B|18-24|Sí|1|M-Eq|0|3|6|10",
  "Culantrillo|Adiantum raddianum|3|A|18-24|Sí|1|F-Eq|0|3|4|7",
  "Cuerno de alce|Platycerium bifurcatum|3|A|18-26|Sí|4|F-Eq|0|3|5|8",
  "Planta de aire pequeña|Tillandsia ionantha|2|C|18-26|Sí|-|-|0|2|7|10|inmersion",
  "Planta de aire grande|Tillandsia xerographica|2|C|18-26|Sí|-|-|0|2|7|12|inmersion",
  "Bromelia estrella|Guzmania lingulata|3|A|18-26|Sí|4|M-Flo|0|2|8|12|tanque",
  "Espada de fuego|Vriesea splendens|3|A|18-26|Sí|4|M-Flo|0|2|8|12|tanque",
  "Bromelia urna|Aechmea fasciata|3|A|18-26|Sí|4|M-Flo|0|2|8|12|tanque",
  "Clivia|Clivia miniata|3|B|18-24|No|1|M-Flo|1|2|8|14",
  "Violeta del cabo|Streptocarpus saxorum|3|B|18-24|No|1|M-Flo|0|2|6|9",
  "Trébol morado|Oxalis triangularis|2|B|18-24|Sí|1|M-Flo|1|2|6|10",
  "Ciclamen|Cyclamen persicum|3|B|15-20|No|1|M-Flo|1|3|5|8",
  "Alegría|Impatiens walleriana|3|A|18-24|Sí|1|F-Flo|0|1|4|7",
  "Prímula|Primula obconica|3|B|15-20|Sí|1|M-Flo|1|2|5|8",
  "Gardenia|Gardenia jasminoides|2|A|18-24|Sí|3|M-Flo|0|3|4|7",
  "Camelia|Camellia japonica|3|B|15-22|Sí|3|M-Flo|1|3|4|7",
  "Cactus africano|Euphorbia trigona|1|C|18-27|No|2|M-Eq|1|1|12|20",
  "Corona de Cristo|Euphorbia milii|1|C|18-27|No|2|M-Flo|1|2|10|18",
  "Lengua de vaca|Gasteria bicolor|2|C|16-26|No|2|M-Eq|0|1|12|18",
  "Piedras vivas|Lithops spp.|1|C|18-24|No|2|M-Eq|0|3|14|24",
  "Dedos de bebé|Fenestraria rhopalophylla|1|C|18-24|No|2|M-Eq|0|3|14|24",
  "Suculenta de fieltro|Senecio haworthii|1|C|18-26|No|2|M-Eq|1|2|12|20",
  "Rosa del desierto|Adenium obesum|1|C|20-28|No|2|M-Flo|1|3|10|18",
  "Suculenta colgante|Aptenia cordifolia|1|C|16-26|No|2|M-Eq|0|1|10|16",
  "Planta de aluminio|Pilea cadierei|3|B|18-24|Sí|1|M-Eq|0|2|6|10",
  "Planta de artillería|Pilea microphylla|3|B|18-24|Sí|1|M-Eq|0|2|6|10",
  "Planta de nervios|Fittonia albivenis|3|A|18-24|Sí|1|M-Eq|0|2|4|7",
  "Planta del beso|Hypoestes phyllostachya|3|B|18-24|Sí|1|M-Eq|0|2|5|8",
  "Lágrimas de bebé|Soleirolia soleirolii|3|A|15-22|Sí|1|M-Eq|0|2|4|7",
  "Hiedra de uva|Cissus rhombifolia|3|B|16-24|Sí|1|M-Eq|0|1|6|10",
  "Hiedra inglesa|Hedera helix|3|B|10-22|Sí|1|M-Eq|1|1|6|9",
  "Albahaca|Ocimum basilicum|1|A|18-26|Sí|1|F-Eq|0|2|4|7|poda",
  "Menta|Mentha spicata|1|A|15-25|Sí|1|F-Eq|0|2|4|7|poda",
  "Perejil|Petroselinum crispum|1|B|15-24|Sí|1|F-Eq|0|2|4|7|poda",
  "Geranio|Pelargonium hortorum|1|B|10-28|No|1|F-Flo|1|1|5|8",
  "Hortensia|Hydrangea macrophylla|3|A|10-25|No|3|M-Flo|1|2|4|7",
  "Lavanda|Lavandula angustifolia|1|C|8-30|No|2|-|1|1|9|14",
  "Romero|Salvia rosmarinus|1|C|8-30|No|2|-|0|1|8|12",
  "Jazmín|Jasminum polyanthum|1|B|10-26|No|1|M-Flo|0|2|5|8",
  "Hibisco|Hibiscus rosa-sinensis|1|B|15-30|No|1|F-Flo|0|2|5|8",
  "Buganvilla|Bougainvillea spectabilis|1|C|12-32|No|2|M-Flo|0|2|7|10",
  "Limonero|Citrus limon|1|B|10-30|No|1|M-Flo|0|2|5|8",
  "Olivo|Olea europaea|1|C|5-32|No|2|-|0|1|9|15",
  "Falso jazmín|Trachelospermum jasminoides|1|B|8-30|No|1|M-Flo|0|1|5|9",
  "Lantana|Lantana camara|1|C|12-32|No|2|M-Flo|1|1|6|10",
  "Jazmín azul|Plumbago auriculata|1|B|12-32|No|1|M-Flo|0|1|5|9",
  "Fucsia|Fuchsia hybrida|3|B|10-24|Sí|1|F-Flo|0|2|4|7",
  "Pensamiento|Viola cornuta|1|B|3-20|No|1|M-Flo|0|1|4|7",
  "Clavel|Dianthus caryophyllus|1|C|8-28|No|2|M-Flo|0|1|6|10",
  "Rosal mini|Rosa chinensis|1|B|8-30|No|1|F-Flo|0|2|4|7",
  "Crisantemo|Chrysanthemum morifolium|1|B|10-25|No|1|M-Flo|1|1|4|7",
  "Azalea|Rhododendron simsii|3|B|5-25|Sí|3|M-Flo|1|3|4|6",
  "Pieris|Pieris japonica|3|B|5-28|No|3|M-Flo|1|2|5|8",
  "Skimmia|Skimmia japonica|3|B|0-25|No|3|M-Eq|1|1|5|9",
  "Nandina|Nandina domestica|2|B|0-30|No|1|M-Eq|1|1|6|10",
  "Fotinia|Photinia fraseri|1|B|0-32|No|1|M-Eq|0|1|6|10",
  "Bambú no invasivo|Fargesia murielae|3|A|0-28|No|1|M-Eq|0|1|4|6",
  "Capuchina|Tropaeolum majus|1|C|8-28|No|1|-|0|1|5|8",
  "Glicinia|Wisteria sinensis|1|B|5-32|No|1|M-Flo|1|3|5|9",
  "Pasionaria|Passiflora caerulea|1|B|8-32|No|1|M-Flo|0|2|5|9",
  "Bignonia|Campsis radicans|1|C|5-35|No|1|-|0|1|6|10",
  "Vincapervinca|Vinca major|3|B|8-28|No|1|M-Eq|1|1|5|9",
  "Hosta|Hosta hybrida|4|A|8-26|No|1|M-Eq|1|1|4|6",
  "Heuchera|Heuchera hybrida|3|B|8-28|No|1|M-Eq|0|1|5|9",
  "Astilbe|Astilbe hybrida|3|A|8-24|No|1|M-Flo|0|2|4|6",
  "Bergenia|Bergenia cordifolia|3|B|0-28|No|1|M-Eq|0|1|6|10",
  "Yuca|Yucca elephantipes|1|C|13-30|No|2|M-Eq|1|1|10|18",
  "Sagú|Cycas revoluta|1|C|13-30|No|2|M-Eq|1|1|10|16",
  "Pino de Norfolk|Araucaria heterophylla|2|B|13-24|Sí|1|M-Eq|0|2|6|9",
  "Poinsetia|Euphorbia pulcherrima|2|B|15-24|No|1|M-Eq|1|2|6|10",
  "Amarilis|Hippeastrum hybridum|2|C|15-26|No|2|M-Flo|1|2|9|15",
  "Planta china|Pilea peperomioides|2|B|15-26|No|1|M-Eq|0|1|7|12",
  "Bananera enana|Musa acuminata|1|A|18-30|Sí|1|F-Eq|0|2|5|8",
  "Begonia de flor|Begonia semperflorens|3|B|13-28|No|1|F-Flo|1|1|5|8",
  "Schefflera enana|Schefflera arboricola|2|B|15-27|Mod|1|M-Eq|1|1|7|12",
  "Coleo|Plectranthus scutellarioides|2|B|15-28|Sí|1|F-Eq|1|1|5|8||plectranthus scutellaroides,solenostemon",
  "Haworthia limifolia|Haworthia limifolia|2|C|15-26|No|2|M-Eq|0|1|12|18||haworthiopsis limifolia,tabla de lavar",
  "Monstera obliqua|Monstera obliqua|3|A|18-27|Sí|1|F-Eq|1|3|5|8",
  "Monstera peru|Monstera karstenianum|2|B|18-27|Sí|1|F-Eq|1|1|6|10",
  "Monstera standleyana|Monstera standleyana|2|B|18-27|Sí|1|F-Eq|1|2|6|10",
  "Poto n'joy|Epipremnum aureum 'N'Joy'|2|B|16-26|Sí|1|F-Eq|1|1|7|12",
  "Poto marble queen|Epipremnum aureum 'Marble Queen'|2|B|16-26|Sí|1|F-Eq|1|1|7|12",
  "Filodendro brasil|Philodendron hederaceum 'Brasil'|2|B|18-27|Sí|1|F-Eq|1|1|7|12",
  "Filodendro micans|Philodendron hederaceum 'Micans'|2|B|18-27|Sí|1|F-Eq|1|1|7|12",
  "Filodendro verrucosum|Philodendron verrucosum|2|B|18-26|Sí|1|F-Eq|1|3|6|9",
  "Anturio clarinervium|Anthurium clarinervium|2|B|18-27|Sí|4|F-Eq|1|3|6|9",
  "Anturio cristalino|Anthurium crystallinum|2|B|18-27|Sí|4|F-Eq|1|3|6|9",
  "Alocasia frydek|Alocasia micholitziana|2|A|20-27|Sí|1|F-Eq|1|3|4|7",
  "Alocasia silver dragon|Alocasia baginda|2|B|20-27|Sí|1|F-Eq|1|3|5|8",
  "Colocasia|Colocasia esculenta|1|A|18-30|Sí|1|F-Eq|0|2|4|6",
  "Calathea medallion|Goeppertia veitchiana|3|A|18-24|Sí|1|F-Eq|0|3|5|8",
  "Calathea white star|Goeppertia majestica|3|A|18-24|Sí|1|F-Eq|0|3|5|8",
  "Stromanthe|Stromanthe sanguinea|3|A|18-24|Sí|1|F-Eq|0|3|5|8",
  "Ctenanthe setosa|Ctenanthe setosa|3|A|18-24|Sí|1|F-Eq|0|2|5|8",
  "Maranta kerchoveana|Maranta leuconeura 'Kerchoveana'|3|A|18-24|Sí|1|F-Eq|0|2|5|8",
  "Begonia rex|Begonia rex-cultorum|2|B|18-24|No|1|M-Flo|1|2|6|9",
  "Begonia hoja de arce|Begonia ricinifolia|2|B|18-26|No|1|M-Flo|1|2|6|10",
  "Peperomia rosso|Peperomia caperata 'Rosso'|3|B|18-26|Mod|1|M-Eq|0|1|7|12",
  "Peperomia hope|Peperomia 'Hope'|3|B|18-26|Mod|1|M-Eq|0|1|8|12",
  "Peperomia tortuga|Peperomia prostrata|3|B|18-26|Mod|1|M-Eq|0|2|7|12",
  "Pilea amistad|Pilea involucrata|3|B|18-24|Sí|1|M-Eq|0|2|5|8",
  "Pilea plateada|Pilea glauca|3|B|18-24|Sí|1|M-Eq|0|2|6|9",
  "Fittonia rosa|Fittonia albivenis 'Rosso'|3|A|18-24|Sí|1|M-Eq|0|2|4|7",
  "Scindapsus treubii|Scindapsus treubii|2|B|18-26|Sí|1|F-Eq|1|1|8|14",
  "Dischidia botones|Dischidia nummularia|2|B|18-26|Sí|4|M-Eq|0|2|6|10",
  "Dischidia corazones|Dischidia ruscifolia|2|B|18-26|Sí|4|M-Eq|0|2|6|10",
  "Hoya corazón|Hoya kerrii|2|C|18-27|No|2|M-Eq|0|1|12|18",
  "Hoya bella|Hoya bella|2|B|18-26|Sí|4|M-Flo|0|2|8|12",
  "Hoya pubicalyx|Hoya pubicalyx|2|B|18-27|Sí|1|M-Flo|0|1|9|14",
  "Rhipsalis|Rhipsalis baccifera|3|B|16-26|Sí|4|M-Eq|0|1|7|12",
  "Cactus pez|Selenicereus anguliger|2|B|16-26|Sí|4|M-Flo|0|2|8|12||epiphyllum anguliger",
  "Rhipsalis coral|Rhipsalis cereuscula|3|B|16-26|Sí|4|M-Eq|0|1|7|12",
  "Bambú de la suerte|Dracaena sanderiana|3|A|18-26|Sí|-|M-Eq|1|1|5|8|agua",
  "Palmera bambú|Rhapis excelsa|3|B|13-26|Sí|1|M-Eq|0|1|6|10",
  "Palmera datilera enana|Phoenix roebelenii|2|B|16-28|Sí|1|M-Eq|0|2|6|9",
  "Palma cola de pez|Caryota mitis|2|B|18-27|Sí|1|M-Eq|0|2|6|9",
  "Chamaedorea metálica|Chamaedorea metallica|3|B|16-25|Sí|1|M-Eq|0|1|6|10",
  "Helecho pie de conejo|Davallia fejeensis|3|B|16-24|Sí|4|F-Eq|0|2|5|8",
  "Pteris|Pteris cretica|3|A|16-24|Sí|1|F-Eq|0|2|4|7",
  "Helecho espada|Blechnum gibbum|3|A|16-24|Sí|1|F-Eq|0|2|5|8",
  "Dendrobium|Dendrobium nobile|2|B|16-26|Sí|4|M-Flo|0|2|7|12",
  "Oncidium|Oncidium hybrida|2|B|16-26|Sí|4|M-Flo|0|2|7|10",
  "Cattleya|Cattleya hybrida|2|B|16-26|Sí|4|M-Flo|0|3|7|10",
  "Orquídea joya|Ludisia discolor|3|B|18-26|Sí|4|M-Eq|0|2|6|9",
  "Drosera|Drosera capensis|1|A|15-30|No|4|-|0|2|3|5|destilada",
  "Venus atrapamoscas|Dionaea muscipula|1|A|10-32|No|4|-|0|3|3|5|destilada",
  "Sarracenia|Sarracenia purpurea|1|A|5-32|No|4|-|0|2|3|5|destilada",
  "Nepenthes|Nepenthes alata|3|A|18-28|Sí|4|-|0|3|4|6|destilada",
  "Asiento de suegra|Echinocactus grusonii|1|C|15-30|No|2|-|0|1|14|24",
  "Cactus dedal|Mammillaria hahniana|1|C|15-30|No|2|-|0|1|14|24",
  "Cereus|Cereus repandus|1|C|15-32|No|2|-|0|1|14|24",
  "Orejas de conejo|Opuntia microdasys|1|C|15-32|No|2|-|0|2|14|24",
  "Agave|Agave americana|1|C|8-35|No|2|-|0|1|14|24",
  "Aloe aristata|Aloe aristata|1|C|15-28|No|2|-|0|1|12|20",
  "Haworthia cooperi|Haworthia cooperi|2|C|15-26|No|2|M-Eq|0|1|12|18",
  "Haworthia cebra|Haworthiopsis attenuata|2|C|15-26|No|2|M-Eq|0|1|12|18",
  "Crassula collar|Crassula perforata|1|C|15-26|No|2|M-Eq|0|1|12|18",
  "Crassula musgosa|Crassula muscosa|1|C|15-26|No|2|M-Eq|0|1|12|18",
  "Senecio tiza|Curio talinoides|1|C|15-28|No|2|M-Eq|1|1|12|20",
  "Echeveria lila|Echeveria lilacina|1|C|15-26|No|2|M-Eq|0|1|12|20",
  "Graptopetalum|Graptopetalum paraguayense|1|C|15-28|No|2|M-Eq|0|1|12|18",
  "Pachyfito|Pachyphytum oviferum|1|C|15-26|No|2|M-Eq|0|1|12|20",
  "Aeonium|Aeonium arboreum|1|C|10-28|No|2|M-Eq|0|1|10|16",
  "Siempreviva|Sempervivum tectorum|1|C|0-30|No|2|-|0|1|10|16",
  "Sedum dorado|Sedum adolphii|1|C|10-30|No|2|M-Eq|0|1|10|16",
  "Portulacaria|Portulacaria afra|1|C|15-28|No|2|M-Eq|0|1|10|16",
  "Kalanchoe peludo|Kalanchoe tomentosa|1|C|15-28|No|2|M-Eq|1|1|12|18",
  "Kalanchoe pala|Kalanchoe thyrsiflora|1|C|15-28|No|2|M-Eq|1|1|12|18",
  "Euphorbia bola|Euphorbia obesa|1|C|18-30|No|2|-|1|2|14|24",
  "Candelabro|Euphorbia lactea|1|C|18-32|No|2|-|1|1|12|20",
  "Planta coral|Pedilanthus tithymaloides|1|B|15-30|No|2|M-Eq|1|2|8|14",
  "Jatrofa|Jatropha podagrica|1|C|18-32|No|2|M-Eq|1|2|10|18",
  "Pachipodio|Pachypodium lamerei|1|C|18-32|No|2|M-Eq|1|2|12|20",
  "Jade gollum|Crassula ovata 'Gollum'|1|C|15-26|No|2|M-Eq|1|1|12|20",
  "Faucia tigre|Faucaria tigrina|1|C|15-26|No|2|M-Eq|0|1|12|20",
  "Geranio hiedra|Pelargonium peltatum|1|B|10-30|No|1|F-Flo|1|1|5|8||gitanilla",
  "Margarita común|Bellis perennis|1|B|5-25|No|1|M-Flo|0|1|4|7",
  "Petunia|Petunia hybrida|1|B|10-30|No|1|F-Flo|0|1|4|7",
  "Surfinia|Petunia 'Surfinia'|1|B|10-30|No|1|F-Flo|0|1|4|7",
  "Gerbera|Gerbera jamesonii|1|B|12-26|No|1|F-Flo|0|2|5|8",
  "Margarita africana|Osteospermum ecklonis|1|B|8-28|No|1|M-Flo|0|1|5|8",
  "Verbena|Verbena hybrida|1|B|10-30|No|1|F-Flo|0|1|4|7",
  "Gazania|Gazania rigens|1|C|8-30|No|2|M-Flo|0|1|7|12",
  "Calibrachoa|Calibrachoa hybrida|1|B|10-28|No|1|F-Flo|0|1|4|7",
  "Lobelia|Lobelia erinus|1|A|10-24|No|1|F-Flo|0|2|4|6",
  "Aliso de mar|Lobularia maritima|1|B|8-26|No|1|M-Flo|0|1|5|8",
  "Clavelina|Dianthus deltoides|1|C|5-28|No|2|M-Flo|0|1|6|10",
  "Zinnia|Zinnia elegans|1|B|15-32|No|1|F-Flo|0|1|5|8",
  "Cosmos|Cosmos bipinnatus|1|C|10-32|No|2|M-Flo|0|1|6|10",
  "Girasol|Helianthus annuus|1|B|10-32|No|1|M-Flo|0|1|5|8",
  "Tagete|Tagetes patula|1|B|10-32|No|1|M-Flo|0|1|5|8",
  "Caléndula|Calendula officinalis|1|B|8-28|No|1|M-Flo|0|1|5|8",
  "Boca de dragón|Antirrhinum majus|1|B|8-28|No|1|M-Flo|0|1|5|8",
  "Alhelí|Matthiola incana|1|B|8-25|No|1|M-Flo|0|2|5|8",
  "Guisante de olor|Lathyrus odoratus|1|B|8-25|No|1|M-Flo|1|2|4|7",
  "Fresa|Fragaria x ananassa|1|B|8-28|No|1|F-Flo|0|1|4|7",
  "Tomate cherry|Solanum lycopersicum|1|A|15-32|No|1|F-Flo|0|2|3|5",
  "Pimiento|Capsicum annuum|1|B|15-32|No|1|F-Flo|0|2|4|6",
  "Orégano|Origanum vulgare|1|C|8-30|No|2|-|0|1|7|12",
  "Tomillo|Thymus vulgaris|1|C|5-30|No|2|-|0|1|8|14",
  "Salvia común|Salvia officinalis|1|C|5-30|No|2|-|0|1|8|14",
  "Cebollino|Allium schoenoprasum|1|B|8-28|No|1|M-Eq|0|1|4|7",
  "Cilantro|Coriandrum sativum|1|B|10-25|No|1|M-Eq|0|2|4|6",
  "Melisa|Melissa officinalis|1|B|8-28|No|1|M-Eq|0|1|5|8",
  "Naranjo|Citrus sinensis|1|B|10-30|No|1|M-Flo|0|2|5|8",
  "Mandarino|Citrus reticulata|1|B|10-30|No|1|M-Flo|0|2|5|8",
  "Vid|Vitis vinifera|1|B|5-35|No|1|M-Flo|0|2|5|9",
  "Higuera|Ficus carica|1|B|5-35|No|1|M-Eq|0|1|6|10",
  "Granado|Punica granatum|1|C|5-35|No|2|M-Flo|0|1|7|12",
  "Arándano|Vaccinium corymbosum|1|B|5-28|No|3|M-Flo|0|2|4|7",
  "Boj|Buxus sempervirens|3|B|0-30|No|1|M-Eq|1|1|6|10",
  "Laurel|Laurus nobilis|1|B|5-30|No|1|M-Eq|0|1|6|10",
  "Mirto|Myrtus communis|1|B|5-32|No|1|M-Eq|0|1|6|10",
  "Pitósporo|Pittosporum tobira|1|B|0-30|No|1|M-Eq|1|1|6|10",
  "Evónimo|Euonymus japonicus|1|B|0-30|No|1|M-Eq|1|1|6|10",
  "Adelfa|Nerium oleander|1|C|0-35|No|2|M-Flo|1|2|7|12",
  "Solano jazminero|Solanum jasminoides|1|B|8-30|No|1|M-Flo|1|2|5|9",
  "Ipomea|Ipomoea purpurea|1|B|12-32|No|1|M-Flo|1|1|4|7",
  "Thunbergia|Thunbergia alata|1|B|12-30|No|1|F-Flo|0|1|4|7",
  "Abutilón|Abutilon megapotamicum|1|B|10-28|No|1|F-Flo|0|2|5|8",
  "Brezo|Erica carnea|1|B|0-25|No|3|M-Flo|0|2|5|8",
  "Calluna|Calluna vulgaris|1|B|0-25|No|3|M-Flo|0|2|5|8",
  "Gaulteria|Gaultheria procumbens|2|B|0-25|No|3|M-Flo|0|1|5|8",
  "Mahonia|Mahonia aquifolium|3|B|0-28|No|3|M-Eq|1|1|6|10",
  "Aucuba|Aucuba japonica|4|B|0-28|No|1|M-Eq|1|1|6|10",
  "Fatsia|Fatsia japonica|4|B|0-25|No|1|M-Eq|0|1|5|9",
  "Helecho macho|Dryopteris filix-mas|4|B|0-25|No|1|M-Eq|0|1|5|8",
  "Polístico|Polystichum setiferum|4|B|0-25|No|1|M-Eq|0|1|5|8",
  "Eléboro|Helleborus orientalis|3|B|0-22|No|3|M-Flo|1|2|5|8",
  "Anémona japonesa|Anemone hupehensis|3|B|5-25|No|1|M-Flo|0|1|5|8",
  "Astrantia|Astrantia major|3|B|5-25|No|1|M-Flo|0|1|5|8",
  "Digital|Digitalis purpurea|3|B|5-25|No|1|M-Flo|1|2|5|8",
  "Aquilegia|Aquilegia vulgaris|3|B|5-25|No|1|M-Flo|1|1|5|8",
  "Alquemila|Alchemilla mollis|3|B|5-25|No|1|M-Eq|0|1|5|8",
  "Sedum de otoño|Hylotelephium spectabile|1|C|0-30|No|2|M-Eq|0|1|8|14",
  "Equinácea|Echinacea purpurea|1|B|0-30|No|1|M-Flo|0|1|5|9",
  "Rudbeckia|Rudbeckia fulgida|1|B|0-30|No|1|M-Flo|0|1|5|9",
  "Hemerocalis|Hemerocallis hybrida|1|B|0-32|No|1|M-Flo|0|1|5|9",
  "Lirio de jardín|Iris germanica|1|C|0-32|No|2|M-Flo|1|1|7|12",
  "Tulipán|Tulipa hybrida|1|B|0-22|No|2|M-Flo|1|2|6|9",
  "Narciso|Narcissus hybrida|1|B|0-25|No|2|M-Flo|1|1|6|10",
  "Jacinto|Hyacinthus orientalis|1|B|0-22|No|2|M-Flo|1|1|6|9",
  "Crocus|Crocus vernus|1|B|0-22|No|2|M-Flo|0|1|6|9",
  "Muscari|Muscari armeniacum|1|B|0-25|No|2|M-Flo|0|1|6|9",
  "Allium ornamental|Allium giganteum|1|C|0-30|No|2|M-Flo|1|1|8|12",
  "Dalia|Dahlia hybrida|1|B|10-30|No|1|F-Flo|0|2|4|7",
  "Gladiolo|Gladiolus hybrida|1|B|10-30|No|2|M-Flo|1|2|5|8",
  "Festuca azul|Festuca glauca|1|C|0-30|No|2|-|0|1|8|14",
  "Pennisetum|Pennisetum alopecuroides|1|B|0-32|No|1|-|0|1|6|10",
  "Carex|Carex morrowii|2|B|0-28|No|1|-|0|1|5|9",
  "Ophiopogon|Ophiopogon japonicus|3|B|0-28|No|1|-|0|1|5|9",
  "Liriope|Liriope muscari|3|B|0-28|No|1|-|0|1|6|10",
"Monstera dubia|Monstera dubia|2|B|18-27|Sí|1|F-Eq|1|2|7|12||monstera plata",
  "Epipremnum pinnatum|Epipremnum pinnatum|2|B|16-28|Sí|1|F-Eq|1|1|7|12||poto grande",
  "Philodendron melanochrysum|Philodendron melanochrysum|2|B|18-27|Sí|1|F-Eq|1|3|6|10||filodendro negro",
  "Philodendron pink princess|Philodendron erubescens|2|B|18-27|Sí|1|F-Eq|1|3|6|10||princesa rosa",
  "Anthurium warocqueanum|Anthurium warocqueanum|2|B|18-27|Sí|4|F-Eq|1|3|6|9||anturio reina",
  "Anthurium veitchii|Anthurium veitchii|2|B|18-27|Sí|4|F-Eq|1|3|6|9||anturio rey",
  "Alocasia cuprea|Alocasia cuprea|2|B|20-27|Sí|1|F-Eq|1|3|5|8||alocasia cobre",
  "Alocasia reginula|Alocasia reginula|2|B|20-27|Sí|1|F-Eq|1|3|5|8||alocasia black velvet",
  "Goeppertia rufibarba|Goeppertia rufibarba|3|A|18-24|Sí|1|F-Eq|0|2|5|8||calathea rufibarba",
  "Goeppertia zebrina|Goeppertia zebrina|3|A|18-24|Sí|1|F-Eq|0|2|5|8||calathea cebra",
  "Stromanthe thalia|Stromanthe thalia|3|A|18-24|Sí|1|F-Eq|0|3|5|8||stromanthe tricolor",
  "Ctenanthe oppenheimiana|Ctenanthe oppenheimiana|3|A|18-24|Sí|1|F-Eq|0|2|5|8||ctenanthe tricolor",
  "Pilea mollis|Pilea mollis|3|B|18-24|Sí|1|M-Eq|0|2|5|8||pilea luna",
  "Pilea nummulariifolia|Pilea nummulariifolia|3|B|18-24|Sí|1|M-Eq|0|1|6|9||pilea rastrera",
  "Peperomia rubella|Peperomia rubella|3|B|18-26|Mod|1|M-Eq|0|1|7|12||peperomia pequeña",
  "Peperomia ferreyrae|Peperomia ferreyrae|2|C|18-26|No|2|M-Eq|0|1|10|16||peperomia habichuela",
  "Hoya wayetii|Hoya wayetii|2|B|18-27|Sí|4|M-Flo|0|2|9|14||hoya wayet",
  "Hoya obovata|Hoya obovata|2|B|18-27|Sí|4|M-Flo|0|1|10|16||hoya obovata",
  "Dischidia ovata|Dischidia ovata|2|B|18-26|Sí|4|M-Eq|0|1|6|10||dischidia melón",
  "Ficus umbellata|Ficus umbellata|2|B|18-27|No|1|M-Eq|1|2|6|10||ficus sombrilla",
  "Ficus triangularis|Ficus triangularis|2|B|18-27|No|1|M-Eq|1|2|6|10||ficus triángulo",
  "Polyscias balfouriana|Polyscias balfouriana|2|B|16-27|Sí|1|M-Eq|1|2|6|10||poliscias balfour",
  "Schefflera elegantissima|Schefflera elegantissima|2|B|16-26|Sí|1|M-Eq|1|2|7|12||aralia elegante",
  "Pachira glabra|Pachira glabra|2|B|18-26|Sí|1|M-Eq|0|1|8|12||pachira lisa",
  "Solanum pseudocapsicum|Solanum pseudocapsicum|1|B|12-24|No|1|M-Flo|1|2|5|8||pimiento de Jerusalén",
  "Echeveria agavoides|Echeveria agavoides|1|C|15-26|No|2|M-Eq|0|1|12|20||echeveria agave",
  "Echeveria pulvinata|Echeveria pulvinata|1|C|15-26|No|2|M-Eq|0|1|12|20||echeveria peluche",
  "Graptopetalum amethystinum|Graptopetalum amethystinum|1|C|15-28|No|2|M-Eq|0|1|12|18||lavanda pebble",
  "Aeonium canariense|Aeonium canariense|1|C|10-28|No|2|M-Eq|0|1|10|16||aeonium canario",
  "Crassula capitella|Crassula capitella|1|C|15-26|No|2|M-Eq|0|1|12|18||crassula fogata",
  "Crassula falcata|Crassula falcata|1|C|15-26|No|2|M-Eq|0|2|12|18||crassula hélice",
  "Crassula arborescens|Crassula arborescens|1|C|15-26|No|2|M-Eq|1|1|12|20||jade plateado",
  "Kalanchoe beharensis|Kalanchoe beharensis|1|C|15-28|No|2|M-Eq|0|2|12|18||kalanchoe fieltro",
  "Kalanchoe orgyalis|Kalanchoe orgyalis|1|C|15-28|No|2|M-Eq|0|1|12|18||cucharas de cobre",
  "Kalanchoe pinnata|Kalanchoe pinnata|1|C|15-28|No|2|M-Eq|0|1|10|16||kalanchoe hoja aire",
  "Cotyledon tomentosa|Cotyledon tomentosa|1|C|15-26|No|2|M-Eq|1|1|12|18||pata de oso",
  "Adromischus cristatus|Adromischus cristatus|1|C|15-26|No|2|M-Eq|0|1|12|20||adromischus pestañas",
  "Anacampseros rufescens|Anacampseros rufescens|1|C|15-28|No|2|M-Eq|0|1|12|18||anacampseros",
  "Othonna capensis|Othonna capensis|1|C|15-26|No|2|M-Eq|0|1|10|16||othonna collar",
  "Senecio herreianus|Senecio herreianus|1|C|15-26|No|2|M-Eq|1|1|10|16||collar de lágrimas",
  "Curio repens|Curio repens|1|C|15-28|No|2|M-Eq|0|1|10|16||senecio repens",
  "Euphorbia tirucalli|Euphorbia tirucalli|1|C|18-32|No|2|-|1|2|12|20||árbol de lápices",
  "Aloe brevifolia|Aloe brevifolia|1|C|15-28|No|2|-|0|1|12|20||aloe corto",
  "Aloe juvenna|Aloe juvenna|1|C|15-28|No|2|-|0|1|12|20||aloe dientes tigre",
  "Gymnocalycium mihanovichii|Gymnocalycium mihanovichii|1|C|15-30|No|2|-|0|1|14|24||cactus luna",
  "Gymnocalycium baldianum|Gymnocalycium baldianum|1|C|15-30|No|2|-|0|1|14|24||gymnocalycium rojo",
  "Rebutia minuscula|Rebutia minuscula|1|C|10-28|No|2|-|0|1|12|22||rebutia",
  "Echinopsis chamaecereus|Echinopsis chamaecereus|1|C|10-28|No|2|-|0|1|12|20||cactus erizo colgante",
  "Parodia magnifica|Parodia magnifica|1|C|15-30|No|2|-|0|1|14|24||parodia",
  "Mammillaria elongata|Mammillaria elongata|1|C|15-30|No|2|-|0|1|14|24||dedos de oro",
  "Mammillaria plumosa|Mammillaria plumosa|1|C|15-30|No|2|-|0|1|14|24||mammillaria plumosa",
  "Espostoa lanata|Espostoa lanata|1|C|15-30|No|2|-|0|2|14|24||cactus peludo",
  "Cephalocereus senilis|Cephalocereus senilis|1|C|15-32|No|2|-|0|2|14|24||cabeza de viejo",
  "Cleistocactus strausii|Cleistocactus strausii|1|C|10-30|No|2|-|0|1|14|24||cleistocactus",
  "Astrophytum asterias|Astrophytum asterias|1|C|15-30|No|2|-|0|2|14|24||astrofito estrella",
  "Astrophytum myriostigma|Astrophytum myriostigma|1|C|15-30|No|2|-|0|2|14|24||gorro de obispo",
  "Rhipsalidopsis gaertneri|Rhipsalidopsis gaertneri|2|B|15-24|Sí|4|M-Flo|0|2|8|14||cactus de pascua",
  "Ferocactus glaucescens|Ferocactus glaucescens|1|C|15-32|No|2|-|0|2|14|24||ferocactus",
  "Thelocactus bicolor|Thelocactus bicolor|1|C|15-32|No|2|-|0|1|14|24||thelocactus",
  "Brassia arcuigera|Brassia arcuigera|2|B|16-26|Sí|4|M-Flo|0|3|7|10||orquídea araña",
  "Miltoniopsis hybrida|Miltoniopsis hybrida|2|B|14-24|Sí|4|M-Flo|0|3|7|10||orquídea pensamiento",
  "Cymbidium hybrida|Cymbidium hybrida|2|B|14-26|Sí|4|M-Flo|0|2|7|10||cymbidium",
  "Paphiopedilum insigne|Paphiopedilum insigne|3|B|16-24|Sí|4|M-Flo|0|2|8|12||zapatilla de venus",
  "Zygopetalum hybrida|Zygopetalum hybrida|2|B|16-24|Sí|4|M-Flo|0|2|7|10||zygopetalum",
  "Maxillaria tenuifolia|Maxillaria tenuifolia|2|B|16-26|Sí|4|M-Flo|0|2|7|10||maxillaria coco",
  "Epidendrum radicans|Epidendrum radicans|1|B|15-28|Sí|4|M-Flo|0|1|6|9||epidendrum fuego",
  "Vanda coerulea|Vanda coerulea|2|B|18-30|Sí|4|M-Flo|0|3|5|8||vanda",
  "Neoregelia carolinae|Neoregelia carolinae|2|A|18-26|Sí|4|M-Flo|0|2|8|12|tanque|neoregelia",
  "Billbergia nutans|Billbergia nutans|2|A|15-26|Sí|4|M-Flo|0|1|8|12|tanque|billbergia",
  "Wallisia cyanea|Wallisia cyanea|2|A|18-26|Sí|4|M-Flo|0|1|8|12|tanque|tillandsia cyanea",
  "Cryptanthus bivittatus|Cryptanthus bivittatus|2|A|18-26|Sí|4|M-Flo|0|1|8|12|tanque|estrella terrestre",
  "Aechmea chantinii|Aechmea chantinii|2|A|18-26|Sí|4|M-Flo|0|2|8|12|tanque|aechmea cebra",
  "Vriesea carinata|Vriesea carinata|2|A|18-26|Sí|4|M-Flo|0|1|8|12|tanque|vriesea pequeña",
  "Guzmania conifera|Guzmania conifera|2|A|18-26|Sí|4|M-Flo|0|2|8|12|tanque|guzmania cono",
  "Quesnelia testudo|Quesnelia testudo|2|A|18-26|Sí|4|M-Flo|0|2|8|12|tanque|quesnelia",
  "Platycerium hillii|Platycerium hillii|3|B|16-26|Sí|4|F-Eq|0|2|5|8||cuerno de alce hill",
  "Asplenium antiquum|Asplenium antiquum|3|A|16-26|Sí|1|F-Eq|0|2|5|8||helecho nido japonés",
  "Nephrolepis falcata|Nephrolepis falcata|3|A|16-24|Sí|1|F-Eq|0|2|4|7||helecho espada rizado",
  "Adiantum hispidulum|Adiantum hispidulum|3|A|15-24|Sí|1|F-Eq|0|2|4|7||culantrillo rudo",
  "Pteris ensiformis|Pteris ensiformis|3|A|16-24|Sí|1|F-Eq|0|2|4|7||pteris victoria",
  "Microsorum diversifolium|Microsorum diversifolium|3|B|15-24|Sí|4|F-Eq|0|2|5|8||helecho canguro",
  "Cyrtomium falcatum|Cyrtomium falcatum|3|B|10-24|Sí|1|F-Eq|0|1|5|8||helecho acebo",
  "Athyrium niponicum|Athyrium niponicum|3|A|10-24|Sí|1|F-Eq|0|2|4|7||helecho japonés pintado",
  "Camellia sasanqua|Camellia sasanqua|3|B|5-25|No|3|M-Flo|0|2|4|7||camelia de otoño",
  "Hydrangea paniculata|Hydrangea paniculata|2|B|0-28|No|3|M-Flo|0|1|4|7||hortensia de panículo",
  "Hydrangea quercifolia|Hydrangea quercifolia|3|B|0-28|No|3|M-Flo|0|1|4|7||hortensia hoja roble",
  "Viburnum tinus|Viburnum tinus|2|B|0-28|No|1|M-Eq|0|1|6|10||laurentino",
  "Prunus laurocerasus|Prunus laurocerasus|2|B|0-28|No|1|M-Eq|1|1|6|10||laurel cerezo",
  "Forsythia intermedia|Forsythia intermedia|1|B|0-28|No|1|M-Flo|0|1|5|9||forsitia",
  "Spiraea japonica|Spiraea japonica|1|B|0-30|No|1|M-Flo|0|1|5|9||espirea",
  "Weigela florida|Weigela florida|1|B|0-30|No|1|M-Flo|0|1|5|9||weigela",
  "Philadelphus coronarius|Philadelphus coronarius|1|B|0-30|No|1|M-Flo|0|1|5|9||celinda",
  "Buddleja davidii|Buddleja davidii|1|C|0-32|No|2|M-Flo|0|1|7|12||arbusto mariposas",
  "Cistus ladanifer|Cistus ladanifer|1|C|0-32|No|2|-|0|1|8|14||jara pringosa",
  "Lavandula stoechas|Lavandula stoechas|1|C|0-30|No|2|-|0|1|8|14||lavanda mariposa",
  "Salvia microphylla|Salvia microphylla|1|C|0-30|No|2|-|0|1|7|12||salvia de Graham",
  "Nepeta cataria|Nepeta cataria|1|C|0-30|No|2|-|0|1|7|12||menta de gato",
  "Achillea millefolium|Achillea millefolium|1|C|0-30|No|2|-|0|1|8|14||milenrama",
  "Leucanthemum vulgare|Leucanthemum vulgare|1|B|0-28|No|1|M-Flo|0|1|5|9||margarita común",
  "Espárrago plumoso|Asparagus densiflorus|2|B|15-26|Mod|1|M-Eq|0|1|6|10||asparagus, espárrago de jardín",
  "Gallina y pollitos|Tolmiea menziesii|3|A|12-22|Sí|1|M-Eq|0|1|5|8||tolmiea, planta de la madre",
  "Barba de capuchino|Saxifraga stolonifera|3|A|12-22|Sí|1|M-Eq|0|1|5|8||saxifraga, planta araña colgante",
  "Helecho botón|Pellaea rotundifolia|3|B|14-24|Sí|1|F-Eq|0|2|5|8||pellaea, helecho de hojas redondas",
  "Aralia escudo|Polyscias scutellaria|2|B|16-27|Sí|1|M-Eq|1|2|6|10||poliscias escudo, aralia balfouriana",
  "Árbol serpiente|Radermachera sinica|2|B|16-27|Sí|1|M-Eq|1|2|6|10||radermachera, árbol de China",
  "Ficus Tineke|Ficus elastica tineke|2|B|16-27|No|1|M-Eq|1|2|6|10||ficus variegado, rubber plant tricolor",
  "Maranta Fascinator|Maranta fascinator|3|A|18-24|Sí|1|F-Eq|0|2|5|8||maranta tricolor, planta oración rosa",
  "Poto Perlas y Jade|Epipremnum pearls jade|2|B|16-26|Sí|1|F-Eq|1|1|7|12||potos variegado, pearls and jade",
  "Poto Cebu Blue|Epipremnum cebu blue|2|B|16-28|Sí|1|F-Eq|1|1|7|12||poto azul, cebu blue",
  "Filodendro Congo|Philodendron congo|2|B|18-27|Sí|1|F-Eq|1|2|7|12||congo rojo, filodendro compacto",
  "Filodendro Xanadu|Philodendron xanadu|2|B|18-27|Sí|1|F-Eq|1|2|6|10||xanadu, filodendro enano",
  "Alocasia Sarian|Alocasia sarian|2|B|20-27|Sí|1|F-Eq|1|3|5|8||alocasia sarian, híbrido zebrina",
  "Calathea White Fusion|Calathea white fusion|3|A|18-24|Sí|1|F-Eq|0|3|5|8||calathea blanca, white fusion",
  "Calathea Dottie|Calathea dottie|3|A|18-24|Sí|1|F-Eq|0|3|5|8||calathea rosa, dottie",
  "Dracaena Colorama|Dracaena colorama|2|B|16-26|Sí|1|M-Eq|1|2|7|12||dracaena tricolor, marginata roja",
  "Dracaena Janet Craig|Dracaena janet craig|2|B|16-26|Sí|1|M-Eq|1|1|7|12||dracaena verde, janet craig",
  "Scindapsus Exotica|Scindapsus exotica|2|B|18-26|Sí|1|F-Eq|1|1|8|14||scindapsus plateado, exotica",
  "Peperomia Verticillata|Peperomia verticillata|3|B|18-26|Mod|1|M-Eq|0|1|7|12||peperomia rastrera, verticillata",
  "Hoya Curtisii|Hoya curtisii|2|B|18-27|Sí|4|M-Flo|0|2|9|14||hoya mini, hoya de hojas pequeñas",
  "Ficus Bambino|Ficus bambino|2|B|18-27|No|1|M-Eq|1|2|7|10||ficus lira enano, bambino",
  "Schefflera Gold Capella|Schefflera gold capella|2|B|16-27|Sí|1|M-Eq|1|2|7|12||aralia dorada, schefflera variegada",
  "Pilea Mojito|Pilea mojito|2|B|16-26|Sí|1|M-Eq|0|1|7|12||pilea mojito, china money variegada",
  "Calathea Roseopicta|Calathea roseopicta|3|A|18-24|Sí|1|F-Eq|0|3|5|8||calathea rosa, roseopicta",
  "Tradescantia Sillamontana|Tradescantia sillamontana|1|B|12-26|Mod|1|M-Eq|0|1|7|12||tradescantia peluda, suculenta colgante",
  "Sedum Palmeri|Sedum palmeri|1|C|10-28|No|2|M-Eq|0|1|10|16||sedum español, sedum de jardín",
  "Sedum Angelina|Sedum rupestre|1|C|0-28|No|2|-|0|1|8|14||sedum dorado, stonecrop",
  "Echeveria Lola|Echeveria lola|1|C|15-26|No|2|M-Eq|0|1|12|20||lola, echeveria gris",
  "Echeveria Perle von Nürnberg|Echeveria perle von nurnberg|1|C|15-26|No|2|M-Eq|0|1|12|20||perla de nuremberg, rosa púrpura",
  "Echeveria Black Prince|Echeveria black prince|1|C|15-26|No|2|M-Eq|0|1|12|20||príncipe negro, echeveria negra",
  "Graptoveria Fred Ives|Graptoveria fred ives|1|C|15-28|No|2|M-Eq|0|1|12|18||graptoveria rosa, híbrido",
  "Sedeveria Harry Butterfield|Sedeveria harry butterfield|1|C|15-28|No|2|M-Eq|0|1|12|18||sedeveria verde, híbrido",
  "Crassula Templo de Buda|Crassula buddhas temple|1|C|15-26|No|2|M-Eq|0|2|12|20||templo de buda, crassula columna",
  "Crassula Hobbit|Crassula hobbit|1|C|15-26|No|2|M-Eq|1|1|12|20||crassula hobbit, jade trompeta",
  "Sansevieria Moonshine|Sansevieria moonshine|4|C|15-28|No|2|M-Eq|1|1|12|20||lengua de suegra plateada, moonshine",
  "Sansevieria Golden Hahnii|Sansevieria golden hahnii|4|C|15-28|No|2|M-Eq|1|1|12|20||sansevieria enana dorada, nido de pájaro",
  "Aloe Cameronii|Aloe cameronii|1|C|15-28|No|2|-|0|1|12|20||aloe rojo, aloe de Cameron",
  "Gasteria Little Warty|Gasteria little warty|2|C|15-26|No|2|M-Eq|0|1|12|18||gasteria enana, little warty",
  "Euphorbia Diamond Frost|Euphorbia diamond frost|1|B|15-30|No|2|-|1|1|7|12||euphorbia blanca, diamond frost",
  "Kalanchoe Calandiva|Kalanchoe calandiva|1|C|15-26|No|2|M-Flo|1|1|10|16||calandiva, kalanchoe de flor doble",
  "Echeveria Topsy Turvy|Echeveria topsy turvy|1|C|15-26|No|2|M-Eq|0|1|12|20||echeveria invertida, topsy turvy",
  "Mammillaria Zeilmanniana|Mammillaria zeilmanniana|1|C|15-30|No|2|-|0|1|14|24||mammillaria rosa, zeilmann",
  "Ferocactus Pilosus|Ferocactus pilosus|1|C|15-32|No|2|-|0|2|14|24||ferocactus peludo, barril mexicano",
  "Chumbera|Opuntia ficus-indica|1|C|5-35|No|2|-|0|1|14|24||tuna, higo chumbo, palera",
  "Cylindropuntia Imbricata|Cylindropuntia imbricata|1|C|5-35|No|2|-|0|1|14|24||cactus árbol, cholla",
  "Echinocactus Platyacanthus|Echinocactus platyacanthus|1|C|15-32|No|2|-|0|2|14|24||biznaga, barril de oro",
  "Astrophytum Capricorne|Astrophytum capricorne|1|C|15-30|No|2|-|0|2|14|24||astrofito cuerno de cabra",
  "Miltonia Spectabilis|Miltonia spectabilis|2|B|16-26|Sí|4|M-Flo|0|3|7|10||miltonia, orquídea pensamiento",
  "Oncidium Twinkle|Oncidium twinkle|2|B|16-26|Sí|4|M-Flo|0|2|7|10||oncidium enano, twinkle rojo",
  "Dendrobium Star Class|Dendrobium star class|2|B|16-26|Sí|4|M-Flo|0|2|7|12||dendrobium compacto, star class",
  "Phalaenopsis Bellina|Phalaenopsis bellina|2|B|18-28|Sí|4|M-Flo|0|2|8|12||bellina, orquídea fragante",
  "Phalaenopsis Schilleriana|Phalaenopsis schilleriana|2|B|18-28|Sí|4|M-Flo|0|2|8|12||schilleriana, orquídea moteada",
  "Cattleya Labiata|Cattleya labiata|2|B|16-26|Sí|4|M-Flo|0|3|7|10||cattleya clásica, labiata",
  "Vanda Tricolor|Vanda tricolor|2|B|18-30|Sí|4|M-Flo|0|3|5|8||vanda tricolor, orquídea sin sustrato",
  "Brassavola Nodosa|Brassavola nodosa|2|B|16-28|Sí|4|M-Flo|0|2|7|10||brassavola, dama de noche",
  "Prosthechea Cochleata|Prosthechea cochleata|2|B|16-28|Sí|4|M-Flo|0|2|7|10||orquídea pulpo, cochleata",
  "Epidendrum Ibaguense|Epidendrum ibaguense|1|B|15-28|Sí|4|M-Flo|0|1|6|9||epidendrum crucifijo, ibaguense",
  "Asplenium Bulbiferum|Asplenium bulbiferum|3|A|14-24|Sí|1|F-Eq|0|2|5|8||helecho madre, asplenio bulbífero",
  "Nephrolepis Kimberley Queen|Nephrolepis kimberley queen|3|A|16-24|Sí|1|F-Eq|0|2|4|7||kimberley queen, helecho espada",
  "Adiantum Fragrans|Adiantum fragrans|3|A|15-24|Sí|1|F-Eq|0|2|4|7||culantrillo fragante, adianto",
  "Pteris Tremula|Pteris tremula|3|A|14-24|Sí|1|F-Eq|0|2|4|7||pteris australiano, helecho nervioso",
  "Davallia Bullata|Davallia bullata|3|B|15-24|Sí|4|F-Eq|0|2|5|8||pata de conejo japonesa, davallia",
  "Microsorum Pustulatum|Microsorum pustulatum|3|B|14-24|Sí|4|F-Eq|0|2|5|8||helecho de cuero, microsorum",
  "Pyrrosia Lingua|Pyrrosia lingua|3|B|14-24|Sí|4|F-Eq|0|2|5|8||lengua de dragón, helecho de fieltro",
  "Dryopteris Erythrosora|Dryopteris erythrosora|3|B|10-24|Sí|1|F-Eq|0|1|5|8||helecho otoñal, dryopteris roja",
  "Clematis Montana|Clematis montana|1|B|0-28|No|1|M-Flo|0|1|5|9||clemátide de montaña, trepadora",
  "Clematis Nelly Moser|Clematis nelly moser|1|B|0-28|No|1|M-Flo|0|1|5|9||clemátide rosa, nelly moser",
  "Glicinia Japonesa|Wisteria floribunda|1|B|0-28|No|1|M-Flo|0|2|5|9||glicinia japonesa, cascada morada",
  "Hortensia Annabelle|Hydrangea arborescens|2|B|0-28|No|3|M-Flo|0|1|4|7||annabelle, hortensia blanca",
  "Hortensia Limelight|Hydrangea limelight|2|B|0-28|No|3|M-Flo|0|1|4|7||limelight, hortensia verde",
  "Camelia Debutante|Camellia debutante|3|B|5-25|No|3|M-Flo|0|2|4|7||camelia rosa, debutante",
  "Rododendro Ponticum|Rhododendron ponticum|3|B|0-25|No|3|M-Flo|0|2|4|7||rododendro común, ponticum",
  "Viburno Roseum|Viburnum opulus|2|B|0-28|No|1|M-Eq|0|1|6|10||bola de nieve, viburno",
  "Aligustre|Ligustrum japonicum|2|B|0-28|No|1|M-Eq|0|1|6|10||aligustre japonés, seto",
  "Boj Faulkner|Buxus microphylla|2|B|0-28|No|1|M-Eq|1|1|6|10||boj enano, faulkner",
  "Azahar de México|Choisya ternata|2|B|0-28|No|1|M-Flo|0|1|6|10||choisya, azahar de México",
  "Hebe Great Orme|Hebe great orme|1|B|0-28|No|1|M-Flo|0|1|6|10||hebe rosa, verónica",
  "Escallonia Donard|Escallonia rubra|1|B|0-28|No|1|M-Flo|0|1|6|10||escallonia rosa, donard",
  "Lila de California|Ceanothus thyrsiflorus|1|B|0-28|No|1|M-Flo|0|1|6|10||ceanothus, lila azul",
  "Jara Rosa|Cistus purpureus|1|C|0-32|No|2|-|0|1|8|14||jara morada, estepa",
  "Abelia Edward Goucher|Abelia edward goucher|1|B|0-28|No|1|M-Flo|0|1|6|10||abelia rosa, edward goucher",
  "Loropetalum Fire Dance|Loropetalum fire dance|2|B|0-28|No|3|M-Flo|0|1|6|10||loropetalum rojo, fire dance",
  "Jazmín de Invierno|Jasminum nudiflorum|2|B|0-28|No|1|M-Flo|0|1|6|10||jazmín amarillo, jazmín de San José",
  "Rosa Peace|Rosa peace|1|B|0-28|No|1|M-Flo|0|1|5|9||rosa de la paz, madame a. meilland",
  "Rosa Iceberg|Rosa iceberg|1|B|0-28|No|1|M-Flo|0|1|5|9||rosa blanca, iceberg, floribunda",
  "Clavel de Poeta|Dianthus barbatus|1|B|0-28|No|1|M-Flo|0|1|5|9||clavel de poeta, sweet william",
  "Nomeolvides|Myosotis sylvatica|3|B|0-24|No|1|M-Flo|0|1|5|9||nomeolvides, myosotis",
  "Delphinium Pacific|Delphinium pacific|1|B|0-28|No|1|M-Flo|0|2|5|9||delphinium azul, espuela de caballero",
  "Altramuz|Lupinus russell|1|B|0-28|No|1|M-Flo|0|2|5|9||altramuz azul, lupino",
  "Amapola Oriental|Papaver orientale|1|B|0-28|No|1|M-Flo|0|1|5|9||amapola de jardín, papaver",
  "Fritillaria Meleagris|Fritillaria meleagris|2|B|0-24|No|1|M-Flo|0|1|6|10||fritillaria ajedrez, flor de ajedrez",
  "Liatris Spicata|Liatris spicata|1|B|0-28|No|1|M-Flo|0|1|6|10||liatris, varita de fuego",
  "Crocosmia Lucifer|Crocosmia lucifer|1|B|0-28|No|1|M-Flo|0|1|6|10||crocosmia roja, montbretia",
  "Alstroemeria Inca Ice|Alstroemeria inca ice|1|B|0-28|No|1|M-Flo|0|1|6|10||alstroemeria blanca, lirio de los incas",
  "Fresia Royal Blue|Freesia royal blue|2|B|10-24|No|1|M-Flo|0|1|6|9||fresia azul, fresia perfumada",
  "Palmera Canaria|Phoenix canariensis|1|C|5-35|No|2|-|0|1|14|24||palmera de Canarias, fénix",
  "Palmera de Abanico|Washingtonia robusta|1|C|5-35|No|2|-|0|1|14|24||washingtonia, palmera mexicana",
  "Palmera Resistente|Trachycarpus fortunei|2|B|0-30|No|2|-|0|1|10|16||palmera de China, chusan",
  "Livistona Chinensis|Livistona chinensis|2|B|5-32|No|2|-|0|1|10|16||livistona, palmera fuente",
  "Licuala Grandis|Licuala grandis|3|B|18-30|Sí|2|-|0|2|8|12||licuala, palmera plato",
  "Tomillo Limón|Thymus citriodorus|1|C|0-30|No|2|-|0|1|8|14||tomillo limón, thymus dorado",
  "Helicriso|Helichrysum italicum|1|C|0-32|No|2|-|0|1|8|14||siempreviva amarilla, curry plant",
]

function P(r: string): SpeciesCard {
  const c = r.split("|")
  return {
    common: c[0],
    sci: c[1],
    light: Number(c[2]) as 1 | 2 | 3 | 4,
    water: c[3] as "A" | "B" | "C",
    temp: c[4],
    mist: c[5] as "Sí" | "Mod" | "No",
    substrate: c[6] === "-" ? 0 : Number(c[6]),
    fert: c[7],
    toxic: c[8] === "1",
    difficulty: Number(c[9]) as 1 | 2 | 3,
    ws: Number(c[10]),
    ww: Number(c[11]),
    flags: c[12] ?? "",
    aliases: c[13] ?? "",

  }
}

const ALIASES: Record<string, string> = {
  "Sansevieria trifasciata": "sansevieria,lengua de tigre,dracaena trifasciata,espada de san jorge",
  "Sansevieria cylindrica": "sansevieria boncel,dracaena cylindrica,lanza",
  "Zamioculcas zamiifolia": "zamioculca,zz,planta zz,zamia",
  "Aspidistra elatior": "aspidistra,hoja de hierro,planta de plomo",
  "Chlorophytum comosum": "cinta,lazo de amor,malamadre,planta araña",
  "Aglaonema commutatum": "aglaonema,aglonema",
  "Ficus elastica": "ficus,arbol de goma,gomero,caucho",
  "Ficus lyrata": "ficus lira,higuera hoja de violin,lirata",
  "Ficus benjamina": "benjamina,ficus,laurel de salon",
  "Ficus microcarpa ginseng": "ficus ginseng,bonsai ficus,microcarpa",
  "Schefflera actinophylla": "schefflera,arbol pulpo,heptapleurum",
  "Pachira aquatica": "pachira,arbol del dinero,castaño de guinea",
  "Monstera deliciosa": "monstera,costilla de adan,deliciosa",
  "Monstera adansonii": "adansonii,monstera de agujeros,monstera pequeña",
  "Philodendron hederaceum": "filodendro,philodendron,scandens",
  "Philodendron bipinnatifidum": "filodendro selloum,selloum,thaumatophyllum",
  "Scindapsus pictus": "scindapsus,potos plateado,satin",
  "Epipremnum aureum": "poto,potos,pothos,scindapsus aureus",
  "Rhaphidophora tetrasperma": "mini monstera,rhaphidophora,monstera minima",
  "Calathea orbifolia": "calathea,goeppertia,orbifolia",
  "Calathea makoyana": "calathea pavo,goeppertia makoyana,pavo real",
  "Maranta leuconeura": "maranta,planta oracion,oración",
  "Ctenanthe burle-marxii": "ctenanthe,calathea burle marx",
  "Goeppertia insignis": "calathea lancifolia,lancifolia,calathea",
  "Crassula ovata": "crassula,arbol de jade,jade,planta del dinero",
  "Echeveria elegans": "echeveria,rosa de alabastro,siempreviva",
  "Sedum morganianum": "sedum,cola de burro,trenza de gitana,borracho",
  "Aloe barbadensis": "aloe,aloe vera,sabila",
  "Haworthia fasciata": "haworthia,haworthiopsis,planta cebra",
  "Schlumbergera truncata": "cactus de navidad,santa teresa,schlumbergera",
  "Spathiphyllum wallisii": "spathiphyllum,lirio de paz,cuna de moises,espatifilo",
  "Anthurium andraeanum": "anturio,anthurium,flor de flamenco",
  "Phalaenopsis hybrida": "orquidea,phalaenopsis,orquídea mariposa",
  "Saintpaulia ionantha": "violeta africana,saintpaulia,violeta",
  "Kalanchoe blossfeldiana": "kalanchoe,calanchoe",
  "Begonia maculata": "begonia tamaya,begonia de lunares,tamaya",
  "Dracaena marginata": "dracaena,dracena,marginata,palmera de madagascar",
  "Dracaena fragrans": "dracaena,tronco de brasil,massangeana",
  "Dracaena surculosa": "dracaena,godseffiana,dracena manchada",
  "Chamaedorea elegans": "chamaedorea,palmera de salon,colinia",
  "Dypsis lutescens": "areca,palmera amarilla,chrysalidocarpus",
  "Beaucarnea recurvata": "beaucarnea,pata de elefante,nolina,nolina recurvata",
  "Tradescantia zebrina": "tradescantia,zebrina,amor de hombre",
  "Tradescantia pallida": "tradescantia,purpurina,setcreasea",
  "Ceropegia woodii": "ceropegia,collar de corazones,rosario de corazones",
  "Senecio rowleyanus": "senecio,collar de perlas,curio rowleyanus",
  "Peperomia obtusifolia": "peperomia,peperomia verde",
  "Nephrolepis exaltata": "helecho,nefrolepis,helecho de boston",
  "Asplenium nidus": "asplenium,helecho nido,nido de ave",
  "Pleopeltis polypodioides": "helecho resurreccion,polypodium",
  "Alocasia zebrina": "alocasia,alocasia tigre,zebrina",
  "Alocasia amazonica": "alocasia polly,alocasia,amazonica,polly",
  "Syngonium podophyllum": "syngonium,singonio,nefititis",
  "Philodendron birkin": "philodendron,birkin,filodendro birkin",
  "Philodendron gloriosum": "philodendron,gloriosum,filodendro gloriosum",
  "Monstera siltepecana": "monstera,siltepecana,monstera plateada",
  "Hoya carnosa": "hoya,flor de cera,hoya rosa",
  "Hoya linearis": "hoya,linearis",
  "Peperomia argyreia": "peperomia sandia,peperomia,sandia",
  "Peperomia caperata": "peperomia,caperata",
  "Ficus pumila": "ficus pumila,higuera trepadora,repens",
  "Ficus altissima": "ficus,altissima",
  "Dracaena reflexa": "dracaena,song of india,pleomele",
  "Strelitzia reginae": "strelitzia,ave del paraiso,flor de pajaro",
  "Strelitzia nicolai": "strelitzia gigante,ave del paraiso blanca,nicolai",
  "Howea forsteriana": "kentia,howea,palmera kentia",
  "Ravenea rivularis": "ravenea,palmera majestad",
  "Adiantum raddianum": "culantrillo,adiantum,cabello de venus",
  "Platycerium bifurcatum": "platycerium,cuerno de alce",
  "Tillandsia ionantha": "tillandsia,planta de aire,clavel de aire",
  "Tillandsia xerographica": "tillandsia,xerographica,planta de aire grande",
  "Guzmania lingulata": "guzmania,bromelia,bromelia estrella",
  "Vriesea splendens": "vriesea,espada de fuego,bromelia",
  "Aechmea fasciata": "aechmea,bromelia urna,urna",
  "Clivia miniata": "clivia,lirio de kaffir",
  "Streptocarpus saxorum": "streptocarpus,violeta del cabo",
  "Oxalis triangularis": "oxalis,trebol morado,falsa grana",
  "Cyclamen persicum": "ciclamen,cyclamen,violeta de persia",
  "Impatiens walleriana": "alegria,impatientes,chinita",
  "Primula obconica": "primula,primaveras,prímula",
  "Gardenia jasminoides": "gardenia,jazmin del cabo",
  "Camellia japonica": "camelia,japonica",
  "Euphorbia trigona": "euphorbia,cactus africano,lechera",
  "Euphorbia milii": "euphorbia,corona de cristo,espinas de cristo",
  "Gasteria bicolor": "gasteria,lengua de vaca",
  "Lithops spp.": "lithops,piedras vivas,cactus piedra",
  "Fenestraria rhopalophylla": "fenestraria,dedos de bebe",
  "Senecio haworthii": "senecio,haworthii,cocoons",
  "Adenium obesum": "adenium,rosa del desierto",
  "Aptenia cordifolia": "aptenia,mesembryanthemum,rocio",
  "Pilea cadierei": "pilea,planta de aluminio",
  "Pilea microphylla": "pilea,planta de artilleria,frescura",
  "Fittonia albivenis": "fittonia,mosaico,planta de nervios",
  "Hypoestes phyllostachya": "hypoestes,cara bonita,pegajosa",
  "Soleirolia soleirolii": "soleirolia,helxine,lagrimas de bebe",
  "Cissus rhombifolia": "cissus,hiedra de uva,roicissus",
  "Hedera helix": "hiedra,hedera,yedra",
  "Ocimum basilicum": "albahaca,basilico",
  "Mentha spicata": "menta,hierbabuena,menta verde",
  "Petroselinum crispum": "perejil,perejil rizado",
  "Pelargonium hortorum": "geranio,pelargonium,geranio de pensamiento",
  "Hydrangea macrophylla": "hortensia,francesilla,rosa de japon",
  "Lavandula angustifolia": "lavanda,espliego",
  "Salvia rosmarinus": "romero,rosmarinus",
  "Jasminum polyanthum": "jazmin,jazmin de china",
  "Hibiscus rosa-sinensis": "hibisco,rosa de china,cayena",
  "Bougainvillea spectabilis": "buganvilla,bugambilia,trinitaria",
  "Citrus limon": "limonero,limon,citro",
  "Olea europaea": "olivo,oliva",
  "Trachelospermum jasminoides": "falso jazmin,trachelospermum,jazmin estrella",
  "Lantana camara": "lantana,banderas",
  "Plumbago auriculata": "plumbago,jazmin azul",
  "Fuchsia hybrida": "fucsia,pendientes de la reina,aretillos",
  "Viola cornuta": "pensamiento,violeta,viola",
  "Dianthus caryophyllus": "clavel,dianthus",
  "Rosa chinensis": "rosal,rosa,rosal mini",
  "Chrysanthemum morifolium": "crisantemo,mum",
  "Rhododendron simsii": "azalea,rododendro",
  "Pieris japonica": "pieris,andromeda",
  "Skimmia japonica": "skimmia,skimmia japonesa",
  "Nandina domestica": "nandina,bambu sagrado",
  "Photinia fraseri": "fotinia,red robin",
  "Fargesia murielae": "bambu,fargesia,bambú no invasivo",
  "Tropaeolum majus": "capuchina,nasturtium,tataguagua",
  "Wisteria sinensis": "glicinia,wisteria,glicina",
  "Passiflora caerulea": "pasionaria,passiflora,flor de la pasion",
  "Campsis radicans": "campsis,bignonia,trompeta",
  "Vinca major": "vinca,vincapervinca,hierba doncella",
  "Hosta hybrida": "hosta,funkia",
  "Heuchera hybrida": "heuchera,coral bells",
  "Astilbe hybrida": "astilbe,plumero",
  "Bergenia cordifolia": "bergenia,orejas de elefante",
  "Yucca elephantipes": "yuca,palma yuca,yuca de interior",
  "Cycas revoluta": "cica,cycas,sagú,palma de sagu",
  "Araucaria heterophylla": "araucaria,pino de norfolk,pino de pisos",
  "Euphorbia pulcherrima": "poinsetia,flor de pascua,nochebuena",
  "Hippeastrum hybridum": "amarilis,hippeastrum",
  "Pilea peperomioides": "pilea,planta china,monedita",
  "Musa acuminata": "bananera,musa,platanero enano",
  "Begonia semperflorens": "begonia,begonia de flor,siemperflorens",
  "Schefflera arboricola": "schefflera,arboricola,parasol enano",
  "Plectranthus scutellarioides": "coleus,cretona",
  "Haworthia limifolia": "haworthia,limifolia",
  "Monstera obliqua": "monstera,obliqua",
  "Monstera karstenianum": "monstera peru,karstenianum",
  "Monstera standleyana": "monstera,standleyana",
  "Epipremnum aureum 'N'Joy'": "poto njoy,njoy,epipremnum",
  "Epipremnum aureum 'Marble Queen'": "poto marble,marble queen",
  "Philodendron hederaceum 'Brasil'": "filodendro brasil,brasil",
  "Philodendron hederaceum 'Micans'": "filodendro micans,micans",
  "Philodendron verrucosum": "philodendron,verrucosum",
  "Anthurium clarinervium": "anturio,clarinervium",
  "Anthurium crystallinum": "anturio,crystallinum",
  "Alocasia micholitziana": "alocasia frydek,frydek",
  "Alocasia baginda": "alocasia,silver dragon",
  "Colocasia esculenta": "colocasia,taro,oreja de elefante",
  "Goeppertia veitchiana": "calathea medallion,calathea,medallion",
  "Goeppertia majestica": "calathea white star,white star",
  "Stromanthe sanguinea": "stromanthe,triostar",
  "Ctenanthe setosa": "ctenanthe,princess,calathea setosa",
  "Maranta leuconeura 'Kerchoveana'": "maranta,kerchoveana,pata de conejo",
  "Begonia rex-cultorum": "begonia rex,begonia de hoja,rex",
  "Begonia ricinifolia": "begonia,ricinifolia,hoja de arce",
  "Peperomia caperata 'Rosso'": "peperomia rosso,rosso",
  "Peperomia 'Hope'": "peperomia hope,hope",
  "Peperomia prostrata": "peperomia,string of turtles,tortuga",
  "Pilea involucrata": "pilea,amistad,moon valley",
  "Pilea glauca": "pilea,glauca,aquamarine",
  "Fittonia albivenis 'Rosso'": "fittonia rosa,fittonia rojo",
  "Scindapsus treubii": "scindapsus,treubii,moonlight",
  "Dischidia nummularia": "dischidia,botones",
  "Dischidia ruscifolia": "dischidia,corazones,million hearts",
  "Hoya kerrii": "hoya,corazon,kerrii",
  "Hoya bella": "hoya,bella",
  "Hoya pubicalyx": "hoya,pubicalyx",
  "Rhipsalis baccifera": "rhipsalis,cactus muérdago",
  "Selenicereus anguliger": "cactus pez,epiphyllum,fishbone",
  "Rhipsalis cereuscula": "rhipsalis,cereuscula,coral",
  "Dracaena sanderiana": "bambu de la suerte,bambú de agua,lucky bamboo",
  "Rhapis excelsa": "rhapis,palmera bambu,dama",
  "Phoenix roebelenii": "phoenix,datilera enana,palmera datilera",
  "Caryota mitis": "caryota,cola de pez,palmera",
  "Chamaedorea metallica": "chamaedorea,metalica,mini palmera",
  "Davallia fejeensis": "davallia,helecho pie de conejo,pata de conejo",
  "Pteris cretica": "pteris,helecho,cinta",
  "Blechnum gibbum": "blechnum,helecho espada",
  "Dendrobium nobile": "dendrobium,orquidea",
  "Oncidium hybrida": "oncidium,orquidea,dama danzante",
  "Cattleya hybrida": "cattleya,orquidea",
  "Ludisia discolor": "ludisia,orquidea joya,jewel orchid",
  "Drosera capensis": "drosera,carnivora,rosolio",
  "Dionaea muscipula": "venus,dionaea,atrapamoscas",
  "Sarracenia purpurea": "sarracenia,carnivora,jarra",
  "Nepenthes alata": "nepenthes,carnivora,copas",
  "Echinocactus grusonii": "echinocactus,asiento de suegra,cactus erizo",
  "Mammillaria hahniana": "mammillaria,cactus dedal,viejita",
  "Cereus repandus": "cereus,cactus columna,peruvianus",
  "Opuntia microdasys": "opuntia,orejas de conejo,nopal",
  "Agave americana": "agave,pita,maguey",
  "Aloe aristata": "aloe,aristata,antorcha",
  "Haworthia cooperi": "haworthia,cooperi",
  "Haworthiopsis attenuata": "haworthia cebra,haworthia,zebra",
  "Crassula perforata": "crassula,collar,perforata",
  "Crassula muscosa": "crassula,muscosa,cola de rata",
  "Curio talinoides": "senecio,tiza,senecio tiza",
  "Echeveria lilacina": "echeveria,lilacina,lila",
  "Graptopetalum paraguayense": "graptopetalum,planta fantasma",
  "Pachyphytum oviferum": "pachyphytum,huevito,moonstones",
  "Aeonium arboreum": "aeonium,copa,siempreviva arborea",
  "Sempervivum tectorum": "sempervivum,siempreviva,barba de jupiter",
  "Sedum adolphii": "sedum,adolphii,nussbaumerianum",
  "Portulacaria afra": "portulacaria,arbusto de jade,verdolaga arborea",
  "Kalanchoe tomentosa": "kalanchoe,panda,peludo",
  "Kalanchoe thyrsiflora": "kalanchoe,pala,flapjack",
  "Euphorbia obesa": "euphorbia,obesa,bola",
  "Euphorbia lactea": "euphorbia,lactea,candelabro",
  "Pedilanthus tithymaloides": "pedilanthus,planta coral,euphorbia tithymaloides",
  "Jatropha podagrica": "jatropha,barriga de buda,planta botella",
  "Pachypodium lamerei": "pachypodium,palma de madagascar",
  "Crassula ovata 'Gollum'": "gollum,jade gollum,crassula gollum",
  "Faucaria tigrina": "faucia,tigre,fauces",
  "Pelargonium peltatum": "gitanilla,geranio hiedra,pelargonium",
  "Bellis perennis": "margarita,bellis,margarita comun",
  "Petunia hybrida": "petunia",
  "Petunia 'Surfinia'": "surfinia,petunia colgante",
  "Gerbera jamesonii": "gerbera,margarita del transvaal",
  "Osteospermum ecklonis": "osteospermum,margarita africana,dimorphotheca",
  "Verbena hybrida": "verbena,verbenas",
  "Gazania rigens": "gazania,flor del sol,margarita de sol",
  "Calibrachoa hybrida": "calibrachoa,mini petunia,millon de campanas",
  "Lobelia erinus": "lobelia",
  "Lobularia maritima": "aliso,lobularia,alyssum",
  "Dianthus deltoides": "clavelina,dianthus",
  "Zinnia elegans": "zinnia,mocitas",
  "Cosmos bipinnatus": "cosmos,mirasoles",
  "Helianthus annuus": "girasol,helianthus",
  "Tagetes patula": "tagete,clavel de moro,damasquina",
  "Calendula officinalis": "calendula,maravilla",
  "Antirrhinum majus": "boca de dragon,antirrhinum,conejitos",
  "Matthiola incana": "alheli,matthiola",
  "Lathyrus odoratus": "guisante de olor,lathyrus",
  "Fragaria x ananassa": "fresa,freson",
  "Solanum lycopersicum": "tomate,tomatera,cherry",
  "Capsicum annuum": "pimiento,guindilla,chile",
  "Origanum vulgare": "oregano",
  "Thymus vulgaris": "tomillo",
  "Salvia officinalis": "salvia",
  "Allium schoenoprasum": "cebollino,chives",
  "Coriandrum sativum": "cilantro,coriandro",
  "Melissa officinalis": "melisa,toronjil,cidronela",
  "Citrus sinensis": "naranjo,naranja,citrus",
  "Citrus reticulata": "mandarino,mandarina,clementino",
  "Vitis vinifera": "vid,parra,uva",
  "Ficus carica": "higuera,higo",
  "Punica granatum": "granado,granada",
  "Vaccinium corymbosum": "arandano,blueberry",
  "Buxus sempervirens": "boj,buxus",
  "Laurus nobilis": "laurel,lauro",
  "Myrtus communis": "mirto,arrayan",
  "Pittosporum tobira": "pitosporo,azahar de la china",
  "Euonymus japonicus": "evonimo,euonymus,bonetero",
  "Nerium oleander": "adelfa,nerium,laurel rosa",
  "Solanum jasminoides": "solano,jazmin de paraguas,potato vine",
  "Ipomoea purpurea": "ipomea,campanilla,morning glory",
  "Thunbergia alata": "thunbergia,susana de ojos negros",
  "Abutilon megapotamicum": "abutilon,farolito,farolillo",
  "Erica carnea": "brezo,erica",
  "Calluna vulgaris": "calluna,brezo de verano,brecina",
  "Gaultheria procumbens": "gaulteria,pernettya",
  "Mahonia aquifolium": "mahonia,uva de oregon",
  "Aucuba japonica": "aucuba,laurel manchado",
  "Fatsia japonica": "fatsia,aralia,hoja de castaño",
  "Dryopteris filix-mas": "helecho macho,dryopteris",
  "Polystichum setiferum": "polistico,helecho",
  "Helleborus orientalis": "heleboro,rosa de cuaresma,helleborus",
  "Anemone hupehensis": "anemona,anemone de japon",
  "Astrantia major": "astrantia,estrella",
  "Digitalis purpurea": "digital,dedalera,foxglove",
  "Aquilegia vulgaris": "aquilegia,pajarilla,columbine",
  "Alchemilla mollis": "alquemila,pie de leon",
  "Hylotelephium spectabile": "sedum de otono,hylotelephium,sedum spectabile",
  "Echinacea purpurea": "equinacea,echinacea,coneflower",
  "Rudbeckia fulgida": "rudbeckia,cono de oro",
  "Hemerocallis hybrida": "hemerocalis,lirio de san juan,daylily",
  "Iris germanica": "lirio,iris,lirio de jardin",
  "Tulipa hybrida": "tulipan,tulipa",
  "Narcissus hybrida": "narciso,daffodil",
  "Hyacinthus orientalis": "jacinto,hyacinthus",
  "Crocus vernus": "crocus,azafran silvestre",
  "Muscari armeniacum": "muscari,jacinto de racimo",
  "Allium giganteum": "allium,cebolla ornamental",
  "Dahlia hybrida": "dalia,dahlia,dalia de jardin",
  "Gladiolus hybrida": "gladiolo,gladiolus,espada",
  "Festuca glauca": "festuca,hierba azul",
  "Pennisetum alopecuroides": "pennisetum,rabo de gato,fountain grass",
  "Carex morrowii": "carex,junquillo",
  "Ophiopogon japonicus": "ophiopogon,mondo grass",
  "Liriope muscari": "liriope,cordon",
  
}

export const SPECIES: SpeciesCard[] = RAW.map(P).map(s => ({
  ...s,
  aliases: [s.aliases, ALIASES[s.sci] ?? ""].filter(Boolean).join(","),
}))

export const LIGHT_LABELS: Record<number, string> = {
  1: "☀️ Sol directo",
  2: "🌤️ Indirecta brillante",
  3: "⛅ Semisombra",
  4: "🌥️ Sombra / poca luz",
}

export const WATER_LABELS: Record<string, { label: string; check: string }> = {
  A: { label: "💧 Sustrato siempre húmedo", check: "no dejar secar nunca" },
  B: { label: "💧 Secar 1-2 cm superficial", check: "dedo: solo seca la capa de arriba" },
  C: { label: "💧 Secar completamente", check: "maceta ligera y tierra seca del todo" },
}

export const MIST_LABELS: Record<string, string> = {
  Sí: "💦 Pulverizar a menudo",
  Mod: "💦 Solo verano o con calefacción",
  No: "🚫 No pulverizar",
}

export const SUBSTRATE_LABELS: Record<number, string> = {
  0: "—",
  1: "Universal",
  2: "Mezcla porosa (cactus/suculentas)",
  3: "Sustrato ácido",
  4: "Corteza o musgo",
}

export const DIFF_LABELS: Record<number, string> = {
  1: "🟢 Fácil",
  2: "🟡 Media",
  3: "🔴 Avanzada",
}

export const FLAG_LABELS: Record<string, string> = {
  tanque: "🫗 Echar agua en el centro (cáliz) y renovarla si se estanca",
  inmersion: "🌊 Riego por inmersión ~1 h/semana o pulverizado diario",
  poda: "✂️ Poda frecuente: pinzar puntas para que no espigue",
  agua: "💧 Puede vivir en agua con guijarros; en tierra, sustrato siempre húmedo",
  destilada: "🧪 Solo agua destilada o de lluvia, y nunca abonar",
}

export function fertLabel(f: string): string {
  if (f === "-") return "sin abono relevante"
  const [freq, tipo] = f.split("-")
  const fq = freq === "F" ? "cada 15 días en primavera-verano" : "1 vez al mes en primavera-verano"
  const tp = tipo === "Eq" ? "equilibrado" : "rico en fósforo (floración)"
  return `${fq} · ${tp} · en invierno no`
}

export function searchSpecies(q: string, limit = 6): SpeciesCard[] {
  const n = q.trim().toLowerCase()
  if (n.length < 2) return []
  return SPECIES.filter(
    s =>
      s.sci.toLowerCase().includes(n) ||
      s.common.toLowerCase().includes(n) ||
      s.aliases.toLowerCase().includes(n)
  ).slice(0, limit)
}

export function findSpecies(q: string): SpeciesCard | undefined {
  const n = q.trim().toLowerCase()
  if (!n) return undefined
  return (
    SPECIES.find(s => s.sci.toLowerCase() === n || s.common.toLowerCase() === n) ??
    SPECIES.find(
      s =>
        s.sci.toLowerCase().includes(n) ||
        s.common.toLowerCase().includes(n) ||
        s.aliases.toLowerCase().includes(n)
    )
  )
}